[build]
  publish = "."
  command = ""

[[headers]]
  for = "/index.html"
  [headers.values]
    cache-control = "no-cache"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    cache-control = "no-cache"

[[headers]]
  for = "/sw.js"
  [headers.values]
    cache-control = "no-cache"

[[headers]]
  for = "/icon-*.png"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    # Allow inline JS/CSS and blob: URLs so the app can run and play local videos
    Content-Security-Policy = "default-src 'self'; img-src 'self' blob: data:; media-src 'self' blob:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'self'; connect-src 'self'; worker-src 'self' blob:; manifest-src 'self'; frame-ancestors 'self'"
